import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Provider from '@/components/Providers/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* this add the title to the website like when we open a website and the tab says that website's or page name and adding a title in the top layout will not allow dynamic name changing of the title*/}
      {/* <head>
        <title>Next.Js Basics</title>
      </head> */}

      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html> 
  );
}
